### ISSUE TITLE
Port Projects

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord#18]
# UPDATE

This issue is closed now, future port projects will be tracked and documented with one specific issue including the associated pull request management. New requests will be added to the [backlog](https://github.com/arcticicestudio/nord-atom-syntax/projects/1) until they are moved into the [project board](https://github.com/arcticicestudio/nord/projects) of the version they will be released with.

Pending/Open port project requests in this issue will be moved into single issues.

---

📓  This epic tracks issues for officially supported port project implementations.
It contains general information for earch project like the total process, related issues and (approximate) ETA dates.

Please note that **only official port projects** are supported ❕ 
The reason for this is the goal to provide a consistent- and good quality for all port projects.
This can only be fulfilled by developing and maintaining these projects in one place.
❗️ **This does NOT exclude contributions under any circumstances** ❗️ 
💟 OSS is made of 👩‍💻 contributions 👨‍💻, 🍴 forks and code sharing and I'm happy for every help!

Please take into account that I work as a software developer in the "real world". I hope you understand that the time for a response may vary depending on my freetime ☺️ 
➡️ Also, please make sure to read the *development process* section below for additional information about this issue.

### Development process
Every official port project is developed locally until the first working initial version is ready to be shipped.
This approach has been deliberately chosen to provide **good quality**.

I've made the experience that pushing every change to the public repository before the project even reached a runnable/usable state only leads to confusion of some users that try to use the project productively, but are dissatisfied because it does not work as desired.
A good example are games marked as [Early Access](http://store.steampowered.com/earlyaccessfaq/) on [Steam](http://store.steampowered.com).
There are good reasons to publish a product as soon as possible for sure which are not only seen from a financial perspective like bug detection and the reviews of users to continiously improve the product, but this can not be applied to all software categories.
That's why all port projects are published after passing certain quality tests and reaching a running/usable state.

If the port project you'd like to see is not listed feel free to create a request issue *or* post it below.

  - Editors & IDEs
    - [x] <img src="https://www.gnu.org/software/emacs/favicon.png" width=16 height=16/> Emacs
      ➡️ 🏷 [0.1.0](https://github.com/arcticicestudio/nord-emacs/releases/tag/v0.1.0)
    - [ ]  <img src="https://www.sublimetext.com/favicon.ico" width=16 height=16/> Sublime Text
    - [x] <img src="http://brackets.io/favicon.ico" width=16 height=16/> Brackets
      ➡️ 🏷 [0.1.0](https://github.com/arcticicestudio/nord-brackets/releases/tag/v0.1.0)
    - [x] <img src="https://developer.apple.com/favicon.ico" width=16 height=16/> Xcode
      ➡️ 🏷 [0.1.0](https://github.com/arcticicestudio/nord-xcode/releases/tag/v0.1.0)
  - UI Applications
    - [ ] <img src="https://www.alfredapp.com/favicon.ico" width=16 height=16/> Alfred
    - [ ] <img src="https://www.mozilla.org/media/img/firefox/favicon-196.png" width=16 height=16/> Firefox
  - UI Libraries
    - [ ] <img src="https://www.gtk.org/images/gtk-logo.ico" width=16 height=16/> GTK
  - CLI Applications
    - [x] <img src="https://tmux.github.io/favicon.ico" width=16 height=16/> tmux
      ➡️ 🏷 [0.1.1](https://github.com/arcticicestudio/nord-tmux/releases/tag/v0.1.1)
    - [ ] <img src="https://weechat.org/media/images/favicon.png" width=16 height=16/> WeeChat
    - [ ] <img src="https://conemu.github.io/conemu.ico" width=16 height=16 /> ConEmu

---

### <img src="https://www.gnu.org/software/emacs/favicon.png" width=16 height=16/> Emacs
> An extensible, customizable, free/libre text editor — and more.

🌐 [Official website](https://www.gnu.org/software/emacs/)
<img src="https://assets-cdn.github.com/favicon.ico" width=18 height=18/> <a href="https://github.com/emacs-mirror/emacs">Repository</a> (Mirror)

🏁 Process ▮▮▮▮▮▮▮▮▮▮ `100%`
*ETA*: 2017-03-25 ✔️
➡️ Released on 2017-03-25 with initial version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-emacs/releases/tag/v0.1.0)
➡️ Now available on <a href="https://melpa.org/#/nord-theme"><img src="https://melpa.org/favicon.ico" width=16 height=16/> MELPA</a> ([melpa/melpa #4655](https://github.com/melpa/melpa/pull/4655))

❯ **Title**: Nord Emacs
❯ **Project**: `nord-emacs`
❯ **Backlog**: `-`
❯ **Related issues**:
  -  Request #6 by @jinnovation
  - Unofficial port project for [Spacemacs](http://spacemacs.org) by @bobbypriambodo posted in [#6](https://github.com/arcticicestudio/nord/issues/6#issuecomment-277230680)
  - [Unofficial port project](https://github.com/apierz/nord-emacs) by @apierz posted in [#6](https://github.com/arcticicestudio/nord/issues/6#issuecomment-278502544)

### <img src="https://www.sublimetext.com/favicon.ico" width=16 height=16/> Sublime Text
> Sublime Text is a sophisticated text editor for code, markup and prose.
You'll love the slick user interface, extraordinary features and amazing performance.

🌐 [Official website](https://www.sublimetext.com)

🏁 Process ▮▯▯▯▯▯▯▯▯▯ `10%`
*ETA*: `-`

❯ **Title**: Nord Sublime Text
❯ **Project**: `nord-sublime-text`
❯ **Backlog**: `-`
❯ **Related issues**:
  -  Request #19 by @djstein

### <img src="http://brackets.io/favicon.ico" width=16 height=16/> Brackets
> A modern, open source text editor that understands web design

🌐 [Official website](http://brackets.io)
<img src="https://assets-cdn.github.com/favicon.ico" width=18 height=18/> <a href="https://github.com/adobe/brackets">Repository</a>

🏁 Process ▮▮▮▮▮▮▮▮▮▮ `100%`
*ETA*: ~~2017-04-08~~ 2017-04-15 ✔️
➡️ Released on 2017-04-15 with initial version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-brackets/releases/tag/v0.1.0)
➡️ Now available on the <a href="https://brackets-registry.aboutweb.com"><img src="http://brackets.io/favicon.ico" width=16 height=16/> Brackets Extension Registry</a>

❯ **Title**: Nord Brackets
❯ **Project**: `nord-brackets`
❯ **Backlog**: #18
❯ **Related issues**:
  - Request PR #17 by @jmyser

### <img src="https://developer.apple.com/apple-logo.svg" width=32 height=32/> Xcode
> The Xcode IDE is at the center of the Apple development experience. Tightly integrated with the Cocoa and Cocoa Touch frameworks, Xcode is an incredibly productive environment for building apps for Mac, iPhone, iPad, Apple Watch, and Apple TV.

🌐 [Official website](https://developer.apple.com/xcode/)

🏁 Process ▮▮▮▮▮▮▮▮▮▮  `100%`
*ETA*: 2017-04-23 ✔️
➡️ Released on 2017-04-23 with initial version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-xcode/releases/tag/v0.1.0)

❯ **Title**: Nord Xcode
❯ **Project**: [`nord-xcode`](https://github.com/arcticicestudio/nord-xcode)
❯ **Backlog**: #35
❯ **Related issues**: [arcticicestudio/nord-xcode #1](https://github.com/arcticicestudio/nord-xcode/issues/1)
  - Request #27 by @ornithocoder

---

### <img src="https://www.alfredapp.com/favicon.ico" width=16 height=16/> Alfred
> Alfred is an award-winning app for Mac OS X which boosts your efficiency with hotkeys, keywords, text expansion and more. Search your Mac and the web, and be more productive with custom actions to control your Mac.

🌐 [Official website](https://www.alfredapp.com)

🏁 Process ▮▮▮▮▯▯▯▯▯▯ `40%`
*ETA*: `-`

❯ **Title**: Nord Alfred
❯ **Project**: `nord-alfred`
❯ **Backlog**: `-`
❯ **Related issues**:
  - #14 by @mattpirelli

### <img src="https://www.mozilla.org/media/img/firefox/favicon-196.png" width=48 height=48/> Firefox
> Set the Web free and your mind will follow. Great add-ons for work, fun, privacy, productivity… just about anything!

🌐 [Official website](https://www.mozilla.org/firefox) ([Add-Ons](https://addons.mozilla.org/en-US/firefox/))

🏁 Process ▯▯▯▯▯▯▯▯▯▯ `0%`
*ETA*: `-`

❯ **Title**: Nord Firefox
❯ **Project**: `nord-firefox`
❯ **Backlog**: `-`
❯ **Related issues**:
  - #22  by @hahuang65 

---

### <img src="https://www.gtk.org/images/gtk-logo.ico" width=16 height=16/> GTK
> GTK+, or the GIMP Toolkit, is a multi-platform toolkit for creating graphical user interfaces. Offering a complete set of widgets, GTK+ is suitable for projects ranging from small one-off tools to complete application suites.

🌐 [Official website](https://www.gtk.org)

🏁 Process ▯▯▯▯▯▯▯▯▯▯ `0%`
*ETA*: `-`

❯ **Title**: Nord GTK
❯ **Project**: `nord-gtk`
❯ **Backlog**: `-`
❯ **Related issues**:
  - Request #11 by @d3rrial 

---

### <img src="https://tmux.github.io/logo.png"/>
> tmux is a terminal multiplexer that lets you switch easily between several programs in one terminal, detach them (they keep running in the background) and reattach them to a different terminal. And do a lot more.

🌐 [Official website](https://tmux.github.io)
<img src="https://assets-cdn.github.com/favicon.ico" width=18 height=18/> <a href="https://github.com/tmux/tmux">Repository</a>

🏁 Process ▮▮▮▮▮▮▮▮▮▮ `100%`
*ETA*: 2017-04-20 ✔️
➡️ Released on 2017-04-20 with plugin version 🏷 [0.1.1](https://github.com/arcticicestudio/nord-tmux/releases/tag/v0.1.1)

❯ **Title**: Nord tmux
❯ **Project**: [`nord-tmux`](https://github.com/arcticicestudio/nord-tmux)
❯ **Backlog**: #30
❯ **Related issues**:
  - Request #16 by @heliostatic

### <img src="https://weechat.org/media/images/weechat_logo_small.png" width=48 height=48/> WeeChat
> WeeChat is a fast, light and extensible chat client. It runs on many platforms like Linux, Unix, BSD, GNU Hurd, Mac OS X and Windows (Bash/Ubuntu and Cygwin).

🌐 [Official website](https://weechat.org)
<img src="https://assets-cdn.github.com/favicon.ico" width=18 height=18/> <a href="https://github.com/weechat/weechat">Repository</a>

🏁 Process ▯▯▯▯▯▯▯▯▯▯ `0%`
*ETA*: `-`

❯ **Title**: Nord WeeChat
❯ **Project**: `nord-weechat`
❯ **Backlog**: `-`
❯ **Related issues**:
  - Request #21 by @hahuang65

### <img src="https://conemu.github.io/img/logo-114.png" width=48 height=48/> ConEmu
> ConEmu-Maximus5 is a Windows console emulator with tabs, which presents multiple consoles and simple GUI applications as one customizable GUI window with various features.

🌐 [Official website](https://conemu.github.io)
<img src="https://assets-cdn.github.com/favicon.ico" width=18 height=18/> <a href="https://github.com/Maximus5/ConEmu">Repository</a>

🏁 Process ▮▮▮▮▮▮▮▮▮▮ `100%`
*ETA*: _2017-10-14_
➡️ Initial version 🏷 [0.1.0](https://github.com/arcticicestudio/nord-conemu/releases/tag/v0.1.0) released on 2017-10-14

❯ **Title**: Nord ConEmu
❯ **Project**: [nord-conemu](https://github.com/arcticicestudio/nord-conemu)
❯ **Backlog**: -
❯ **Related issues**:
  - Request #26 by @boogy
  - Initial startup code [#26 (comment)](https://github.com/arcticicestudio/nord/issues/26#issuecomment-292751505) by @cobrabr

**Comment by boogy** [comment]
#26 ConEmu theme

**Comment by cobrabr** [comment]
I've created a Notepad2 theme that I'd like to share: [notepad2_nord.zip](https://github.com/arcticicestudio/nord/files/949513/notepad2_nord.zip)

The settings have been set for most of the available syntax highlighting colours, but could probably use a more thorough look and test. At the very least, it's a headstart. :)

**EDIT:** Updated the ZIP file with a slightly revised version of the INI file.

**Comment by cobrabr** [comment]
How about a theme for Visual Studio 2013/2015/2017? There is a port of sorts at Studio Styles (https://studiostyl.es/schemes/nord-ish), but it's be interesting to have an official port as well.

**Comment by gkatev** [comment]
A theme for geany (http://www.geany.org/) would be interesting

**Comment by arcticicestudio** [comment]
Closing this issue now, future port projects will be resolved with one issue including the associated pull request management. New requests will be added to the [backlog](https://github.com/arcticicestudio/nord-atom-syntax/projects/1) until they are moved into the [project board](https://github.com/arcticicestudio/nord/projects) of the version they will be released with.

Pending/Open port project requests in this issue will be moved into single issues.
