### ISSUE TITLE
Remaining `arcticicestudio` "fade-out" changes

### ISSUE THREAD

**Issue by svengreb** [arcticicestudio/nord#197]
With [the retirement of the _Arctic Ice Studio_ personal & Nord project brand][1] various migrations to [the `svengreb` GitHub account][2] of other projects were also completed within the last weeks. There are also changes in Nord projects like `nordtheme/web` that other projects depended on and can now be adapted as well.
Therefore all Nord projects must adapt these changes which includes…

- [the migration and repository name change of `arcticicestudio/nord-docs`][2] — all references must be updated.
- [the migration of the `arcticicestudio/styleguide-git` repository to the `svengreb` _real-in-person_ identity][3] — all references and used npm packages must be updated.
- [the migration of the `arcticicestudio/styleguide-javascript` repository to the `svengreb` _real-in-person_ identity][4] — all references and used npm packages must be updated.
- [the migration of the `arcticicestudio/styleguide-markdown` repository to the `svengreb` _real-in-person_ identity][5] — all references and used npm packages must be updated.

These changes will be adapted for the following projects:

```[tasklist]
### Tasks
- [ ] https://github.com/nordtheme/.github/issues/26
- [ ] https://github.com/nordtheme/alacritty/issues/35
- [ ] https://github.com/nordtheme/assets/issues/27
- [ ] https://github.com/nordtheme/atom-syntax/issues/73
- [ ] https://github.com/nordtheme/atom-ui/issues/93
- [ ] https://github.com/nordtheme/brackets/issues/12
- [ ] https://github.com/nordtheme/coda/issues/10
- [ ] https://github.com/nordtheme/conemu/issues/8
- [ ] https://github.com/nordtheme/dircolors/issues/34
- [ ] https://github.com/nordtheme/eclipse-syntax/issues/17
- [ ] https://github.com/nordtheme/emacs/issues/124
- [ ] https://github.com/nordtheme/gedit/issues/22
- [ ] https://github.com/nordtheme/gnome-terminal/issues/43
- [ ] https://github.com/nordtheme/guake/issues/10
- [ ] https://github.com/nordtheme/highlightjs/issues/24
- [ ] https://github.com/nordtheme/hyper/issues/40
- [ ] https://github.com/nordtheme/iterm2/issues/17
- [ ] https://github.com/nordtheme/java/issues/15
- [ ] https://github.com/nordtheme/jetbrains/issues/211
- [ ] https://github.com/nordtheme/konsole/issues/16
- [ ] https://github.com/nordtheme/mintty/issues/9
- [ ] https://github.com/nordtheme/nord/issues/198
- [ ] https://github.com/nordtheme/notepadplusplus/issues/23
- [ ] https://github.com/nordtheme/putty/issues/9
- [ ] https://github.com/nordtheme/slack/issues/22
- [ ] https://github.com/nordtheme/sublime-text/issues/39
- [ ] https://github.com/nordtheme/terminal-app/issues/15
- [ ] https://github.com/nordtheme/terminator/issues/20
- [ ] https://github.com/nordtheme/termite/issues/15
- [ ] https://github.com/nordtheme/tilix/issues/21
- [ ] https://github.com/nordtheme/tmux/issues/84
- [ ] https://github.com/nordtheme/vim/issues/341
- [ ] https://github.com/nordtheme/visual-studio-code/issues/265
- [ ] https://github.com/nordtheme/web/issues/243
- [ ] https://github.com/nordtheme/xcode/issues/17
- [ ] https://github.com/nordtheme/xfce-terminal/issues/16
- [ ] https://github.com/nordtheme/xresources/issues/17
```

[1]: https://github.com/orgs/nordtheme/discussions/183#retire-arctic-ice-studio-as-nord-brand
[2]: https://github.com/nordtheme/web/issues/241
[3]: https://github.com/svengreb/styleguide-git/issues/12
[4]: https://github.com/svengreb/styleguide-javascript/issues/88
[5]: https://github.com/svengreb/styleguide-markdown/issues/63
