### ISSUE TITLE
Migrate to MIT license

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/nord#55]
Currently the project code is licensed under the [Apache 2.0][apache] license. This often causes problems when developers want to use the project or code parts of it in another project (mainly code editors and UI frameworks) licensed under a less restricted license.

The project and all of its port projects should migrate to the [MIT license][cal-mit] which is more open, unrestricted and the most used license for open source projects (Facebook recently also [re-licensed React][fr])

### Port Projects

The following port projects must be migrated to adapt to the new license:

* [x] arcticicestudio/nord-alacritty#4
* [x] arcticicestudio/nord-atom-syntax#58
* [x] arcticicestudio/nord-atom-ui#71
* [x] arcticicestudio/nord-brackets#5
* [x] arcticicestudio/nord-coda#4
* [x] arcticicestudio/nord-conemu#4
* [x] arcticicestudio/nord-dircolors#9
* [x] arcticicestudio/nord-eclipse-syntax#5
* [x] arcticicestudio/nord-emacs#58
* [x] arcticicestudio/nord-gedit#8
* [x] arcticicestudio/nord-gnome-terminal#18
* [x] arcticicestudio/nord-guake#5
* [x] arcticicestudio/nord-highlightjs#8
* [x] arcticicestudio/nord-hyper#14
* [x] arcticicestudio/nord-iterm2#7
* [x] arcticicestudio/nord-java#12
* [x] arcticicestudio/nord-jetbrains-editor#30
* [x] arcticicestudio/nord-konsole#8
* [x] arcticicestudio/nord-mintty#4
* [x] arcticicestudio/nord-notepadplusplus#4
* [x] arcticicestudio/nord-putty#4
* [x] arcticicestudio/nord-slack#4
* [x] arcticicestudio/nord-sublime-text#5
* [x] arcticicestudio/nord-terminal-app#4
* [x] arcticicestudio/nord-terminator#10
* [x] arcticicestudio/nord-termite#8
* [x] arcticicestudio/nord-tilix#17
* [x] arcticicestudio/nord-tmux#20
* [x] arcticicestudio/nord-vim#70
* [x] arcticicestudio/nord-visual-studio-code#64
* [x] arcticicestudio/nord-xfce-terminal#8
* [x] arcticicestudio/nord-xcode#5
* [x] arcticicestudio/nord-xresources#6

[apache]: http://www.apache.org/licenses/LICENSE-2.0
[cal-mit]: https://choosealicense.com/licenses/mit/
[fr]: https://code.facebook.com/posts/300798627056246/relicensing-react-jest-flow-and-immutable-js/
